### ISSUE TITLE
Open to edits and contributions?

### ISSUE THREAD

**Issue by mjbear** [joey-melo/netcredz#1]
Hello @joey-melo,

:question: Are you open to contributions and suggestions?

Here are some free suggestions for things I can't edit/submit a PR regarding. :wink:

* There's a misspelling for dependencies in the project description.
* Your project description has unneeded trailing whitespace after "Gaffie" (minor, yeah I know)

With zero ~depedencies~ dependencies, NetCredz extracts credentials from pcap files or live traffic, supporting NTLM, LDAP, HTTP, SMTP, SNMP, Telnet, FTP, and Kerberos, while also detecting DHCPv6 and LLMNR traffic. Inspired by PCredz from Laurent Gaffie

**Comment by joey-melo** [comment]
> Hello @joey-melo,
> 
> ❓ Are you open to contributions and suggestions?
> 
> Here are some free suggestions for things I can't edit/submit a PR regarding. 😉
> 
> * There's a misspelling for dependencies in the project description.
> * Your project description has unneeded trailing whitespace after "Gaffie" (minor, yeah I know)
> 
> With zero ~depedencies~ dependencies, NetCredz extracts credentials from pcap files or live traffic, supporting NTLM, LDAP, HTTP, SMTP, SNMP, Telnet, FTP, and Kerberos, while also detecting DHCPv6 and LLMNR traffic. Inspired by PCredz from Laurent Gaffie

Hi @mjbear, Thank you for the contribution. I will fix that right away. I will open the project to Pull Requests, thanks for pointing it out.
